### ISSUE TITLE
responses for RMonkey don't give the right result

### ISSUE THREAD

**Issue by LoesClephas** [leeper/Rmonkey#3]
I logged in by smlogin and wrote the following code hereafter... I only want results from the first survey and the first three respondents: 

s <- surveylist() 

s1 <- as.character(s[[1]])

r <- respondentlist(s1)
r1 <- as.character(r[[1]])
r2 <- as.character(r[[2]])
r3 <- as.character(r[[3]])

r <- as.array(c(r1,r2, r3))

z <- getresponses(r, s1)
z

console spits out the following: 

[[1]]
Responent ID: 3715806829 

[[2]]
Responent ID: 3715806096 

[[3]]
Responent ID: 3715804951 

attr(,"class")
[1] "sm_response_list"

whereas it should spit out something like (according to API console, response body): 

{
  "status": 0,
  "data": [
    {
      "respondent_id": "3715806829",
      "questions": [
        {
          "answers": [
            {
              "text": "49",
              "row": "0"
            }
          ],
          "question_id": "754179130"
        }
      ]
    },
    {
      "respondent_id": "3715806096",
      "questions": [
        {
          "answers": [
            {
              "text": "28",
              "row": "0"
            }
          ],
          "question_id": "754179130"
        }
      ]
    },
    {
      "respondent_id": "3715804951",
      "questions": [
        {
          "answers": [
            {
              "text": "43",
              "row": "0"
            }
          ],
          "question_id": "754179130"
        }
      ]
    }
  ]
}

Can anybody help me?

**Comment by leeper** [comment]
The JSON data structure that you describe is converted automatically by Rmonkey into an R list, where each respondent is a list element of class `sm_response`. This list structure, which you can see by typing `str(z)` will contain all of the response data. Objects of class `sm_response` have been given [a very compact `print` method](https://github.com/leeper/Rmonkey/blob/master/R/getresponses.r#L39-L43) so as to conserve console space when printing, but your `z` object should contain all of the response data for those respondents, which you can then extract as needed using `$` or `[[`.

**Comment by LoesClephas** [comment]
Thank you leeper for your extensive answer... do you know which package is used for function add_header? 

I am trying to use your function now to make this all work :).

**Comment by LoesClephas** [comment]
Never mind, found it (package httr)

**Comment by LoesClephas** [comment]
What exactly should be the variables to put in the following function you describe: as.data.frame.sm_response <- function(x, details = NULL, ...)

in other words what should I fill in at "x" and at "details"... I am not very good at lists so this is quite confusing for me... Hope you find the time to help me... 

In the end I would like to build a function I can retrieve a datatable per survey with all the responses to all the questions I ask...

**Comment by LoesClephas** [comment]
Or should I write a function myself depending on the type of questions asked in the survey and extracting all numbers by for example: 

z[[1]][2]$questions[[1]]$answers[[1]]$text (which returns a string of 49)?

**Comment by LoesClephas** [comment]
With another survey I get the following error message: 
when using getresponses(r,s1) I get the following error:

Error in lapply(content$data, `class<-`, "sm_response") : 
  attempt to set an attribute on NULL

This might be caused by the fact that the content$status == 0

any idea how to overcome this?

output by API Console: 

{
  "status": 0,
  "data": [
    null,
    {
      "respondent_id": "3707528732",
      "questions": [
        {
          "answers": [
            {
              "text": "33",
              "row": "8512740564"
            },
            {
              "text": "33",
              "row": "8512740565"
            },

**Comment by leeper** [comment]
I think I've fixed this error now. You'll need to reinstall from GitHub (and probably restart R).

I intentionally do not collapse the responses data into anything other than a list because the particular structure of the response can vary by question type. If your questionnaire is quite simple, you should be able to do something like `do.call('rbind.data.frame', z)` and get a data.frame out of the response object. This may not work perfectly, though.

I haven't worked on this package in quite a while, so if you see a solution for how best to return results, let me know or feel free to issue a pull request with changes.

**Comment by hjermann** [comment]
Hi leeper,

I have followed your example to retrieve survey responses, but executing following command:
> getresponses(head(r,100), s[[40]]) #r have total 173 values and s[[40]] is survey, what I'm interested in, I get following error:

$status
[1] 3

$errmsg
[1] "Failed to validate field 'respondent_ids' list schema: Value {u'respondent_id': u'3737439016'} for field '_data' is not of type string"

Am I doing something totally wrong?

**Comment by leeper** [comment]
@hjermann Can you include the output of `str(r)` for me? I think the respondent list structure is not formatted correctly, so SurveyMonkey doesn't know what is being requested.

**Comment by hjermann** [comment]
Hi Thomas,

 

Thank you for quick response :)

 

The result of str(r) is following:

 

> str(r)

List of 173

$ :List of 1

  ..$ respondent_id: chr "3737439016"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3733404977"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3733403715"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3733401364"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3726954132"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3726944981"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3726923782"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3722737671"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3721955795"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3718891225"

  ..- attr(*, "class")= chr "sm_respondent"

$ :List of 1

  ..$ respondent_id: chr "3718349359"

  ..- attr(*, "class")= chr "sm_respondent"

…

 

Best regards,

Hindrek

**Comment by LoesClephas** [comment]
I am still working on a nice function to get a datatable from surveymonkey
stuff... Just not at the moment because I am occupied with other things...
I will get back to that as soon as I have time to work on it again.

Grz,

Loes

2015-02-05 13:06 GMT+01:00 Hindrek Jermann <notifications@github.com>:

> Hi Thomas,
>
>
>
> Thank you for quick response :)
>
>
>
> The result of str(r) is following:
>
>
>
> > str(r)
>
> List of 173
>
> $ :List of 1
>
> ..$ respondent_id: chr "3737439016"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3733404977"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3733403715"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3733401364"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3726954132"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3726944981"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3726923782"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3722737671"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3721955795"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3718891225"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> $ :List of 1
>
> ..$ respondent_id: chr "3718349359"
>
> ..- attr(*, "class")= chr "sm_respondent"
>
> …
>
>
>
> Best regards,
>
> Hindrek
>
>
>
> From: Thomas J. Leeper [mailto:notifications@github.com]
> Sent: Thursday, February 5, 2015 1:40 PM
> To: leeper/Rmonkey
> Cc: Hindrek Jermann
> Subject: Re: [Rmonkey] responses for RMonkey don't give the right result
> (#3)
>
>
>
> @hjermann <https://github.com/hjermann> Can you include the output of
> str(r) for me? I think the respondent list structure is not formatted
> correctly, so SurveyMonkey doesn't know what is being requested.
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/leeper/Rmonkey/issues/3#issuecomment-73033214> . <
> https://github.com/notifications/beacon/AJo1PEGvMFhOZOU5TgL_CB2GBGigUO6Tks5no037gaJpZM4DXIiy.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leeper/Rmonkey/issues/3#issuecomment-73036192>.
>



-- 
___________________________
ir. Loes Clephas
Vreelandgroep Organisatie-adviseurs

T: 035-5423922
M: 06-83440388
E: clephas@vreelandgroep.nl

Soestdijkseweg Zuid 224
3721 AJ  Bilthoven
Postbus 116
3720 AC Bilthoven
KvK-nr 320 86 880

 <https://www.youtube.com/watch?v=bjzVSoZvA7I>
______________________________

**Comment by hjermann** [comment]
Hi Loes,

 

By default jsonlite function fromJSON returns result as data.frame object. Maybe this can be used olso in your functionality?

 

jd<-fromJSON("https://api.github.com/users/hjermann/repos")

 

>class(jd)

[1] “data.frame”

 

 

Regards,

Hindrek

**Comment by leeper** [comment]
@hjermann Try reinstalling from Github (you may need to also then restart R) and try this again. This might have been easy fix (which I've taken care) or it will take a little more work (and I'll have to look into it later).

**Comment by hjermann** [comment]
@leeper Thank you! At the moment I was able to get also getresponses() result.

**Comment by dnchari** [comment]
Hi leeper, I am unable to to convert the responses I get to a data.frame

**Comment by leeper** [comment]
I've just sent a patch that hopefully addresses these issues. @dnchari  @hjermann @LoesClephas, please reinstall from Github and confirm that it is working for you successfully. Note in particular, that you can use the `as.data.frame` method for the `sm_response_list`. I've now imported `plyr::rbind.fill`, which should create a well-formed data.frame from this response list automatically. `getresponses` will still return a list by default, but this can be converted using `as.data.frame`.

**Comment by dnchari** [comment]
Hi Tom,
Thanks. How to get the Survey ID? I would like to get data for a particular survey. I only know the name of the survey.
Thank You,Chari

**Comment by dnchari** [comment]
Hi Tom,

Thanks. How to get the Survey Id? I would like to get the data for a particular survey. I only know the survey name.

Thanks,
Chari

**Comment by leeper** [comment]
@dnchari Use the `surveylist()` function to get a list of all of your surveys.

**Comment by dnchari** [comment]
Yes, that gives the list. How can I select one survey based on the survey name. I only can see survey ID when I look at surveylist().

**Comment by LoesClephas** [comment]
any idea how to solve the following error (where survey is "64820318" and collector is "61684114"). 

In Rstudio: 
respondentlist(survey, collector,,,,,,,,,"first_name",getOption('sm_api_key'),getOption('sm_oauth_token'))

Console: 
Error in respondentlist(survey, collector, , , , , , , , , "first_name",  : 
  client error: (403) Forbidden

respondentlist(survey,collector) works fine... looks like I don't have the authority to retrieve the first name from the collector... why not? 

Kind regards,

**Comment by leeper** [comment]
@LoesClephas Your code is a little unclear to me. You don't need to include the commas,  you can just specify the argument using its name, like `respondentlist(survey, collector, fields = "first_name")`. Is that what you're going for? Seems like it could just be placing the argument in the wrong position.

**Comment by LoesClephas** [comment]
@Thomas Leeper, yes you were right... I am wondering... is it also possible
to retrieve the names of the people that were invited but didn't respond
yet?



2015-03-06 14:10 GMT+01:00 Thomas J. Leeper <notifications@github.com>:

> @LoesClephas <https://github.com/LoesClephas> Your code is a little
> unclear to me. You don't need to include the commas, you can just specify
> the argument using its name, like respondentlist(survey, collector,
> fields = "first_name"). Is that what you're going for? Seems like it
> could just be placing the argument in the wrong position.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leeper/Rmonkey/issues/3#issuecomment-77556136>.
>



-- 
___________________________
ir. Loes Clephas
Vreelandgroep Organisatie-adviseurs

T: 035-5423922
M: 06-83440388
E: clephas@vreelandgroep.nl

Soestdijkseweg Zuid 224
3721 AJ  Bilthoven
Postbus 116
3720 AC Bilthoven
KvK-nr 320 86 880

 <https://www.youtube.com/watch?v=bjzVSoZvA7I>
______________________________

**Comment by leeper** [comment]
@LoesClephas  You should be able to pass "status" as a `field`. I'm not sure exactly what the response will look like (the documentation is vague on that).

**Comment by LoesClephas** [comment]
the response is only whether a response is completed of "started"...
however it doesn't result in a list of people that did not respond at
all... only people that have started to respons or completed the response.

2015-03-06 17:00 GMT+01:00 Thomas J. Leeper <notifications@github.com>:

> @LoesClephas <https://github.com/LoesClephas> You should be able to pass
> "status" as a field. I'm not sure exactly what the response will look
> like (the documentation is vague on that).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leeper/Rmonkey/issues/3#issuecomment-77582810>.
>



-- 
___________________________
ir. Loes Clephas
Vreelandgroep Organisatie-adviseurs

T: 035-5423922
M: 06-83440388
E: clephas@vreelandgroep.nl

Soestdijkseweg Zuid 224
3721 AJ  Bilthoven
Postbus 116
3720 AC Bilthoven
KvK-nr 320 86 880

 <https://www.youtube.com/watch?v=bjzVSoZvA7I>
______________________________

**Comment by leeper** [comment]
@LoesClephas Looks like it's not one of the available statuses: http://stackoverflow.com/a/21439288/2338862

**Comment by LoesClephas** [comment]
that's what I thought...

2015-03-06 17:05 GMT+01:00 Thomas J. Leeper <notifications@github.com>:

> @LoesClephas <https://github.com/LoesClephas> Looks like it's not one of
> the available statuses: http://stackoverflow.com/a/21439288/2338862
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leeper/Rmonkey/issues/3#issuecomment-77583836>.
>



-- 
___________________________
ir. Loes Clephas
Vreelandgroep Organisatie-adviseurs

T: 035-5423922
M: 06-83440388
E: clephas@vreelandgroep.nl

Soestdijkseweg Zuid 224
3721 AJ  Bilthoven
Postbus 116
3720 AC Bilthoven
KvK-nr 320 86 880

 <https://www.youtube.com/watch?v=bjzVSoZvA7I>
______________________________

**Comment by LoesClephas** [comment]
thank you :)

2015-03-06 17:07 GMT+01:00 Loes Clephas <clephas@vreelandgroep.nl>:

> that's what I thought...
>
> 2015-03-06 17:05 GMT+01:00 Thomas J. Leeper <notifications@github.com>:
>
>> @LoesClephas <https://github.com/LoesClephas> Looks like it's not one of
>> the available statuses: http://stackoverflow.com/a/21439288/2338862
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/leeper/Rmonkey/issues/3#issuecomment-77583836>.
>>
>
>
>
> --
> ___________________________
> ir. Loes Clephas
> Vreelandgroep Organisatie-adviseurs
>
> T: 035-5423922
> M: 06-83440388
> E: clephas@vreelandgroep.nl
>
> Soestdijkseweg Zuid 224
> 3721 AJ  Bilthoven
> Postbus 116
> 3720 AC Bilthoven
> KvK-nr 320 86 880
>
>  <https://www.youtube.com/watch?v=bjzVSoZvA7I>
> ______________________________
>
>


-- 
___________________________
ir. Loes Clephas
Vreelandgroep Organisatie-adviseurs

T: 035-5423922
M: 06-83440388
E: clephas@vreelandgroep.nl

Soestdijkseweg Zuid 224
3721 AJ  Bilthoven
Postbus 116
3720 AC Bilthoven
KvK-nr 320 86 880

 <https://www.youtube.com/watch?v=bjzVSoZvA7I>
______________________________

**Comment by dnchari** [comment]
Hi Tom,
Can we store credentials using ROAuth package to build a shiny App? something like
download.file(url="http://curl.haxx.se/ca/cacert.pem",destfile="cacert.pem")
cred = OAuthFactory$new(consumerKey='key',                        consumerSecret='secret',                        authURL='http://localhost:1410',                        response_type = 'code')cred$handshake(cainfo="cacert.pem")save(red, file='myCred.RData')
Please let me know,
Thank You,
Best Regards,Chari

**Comment by leeper** [comment]
@dnchari Rmonkey uses httr for OAuth. The ROAuth package is a separate regime and I make no promises that Rmonkey will work with it. That said, the SurveyMonkey OAuth token is long-lived, so it should be easy to store an OAuth token however you choose to generate it. I'm not a Shiny expert, so I can't speak to exactly how that would work in your context.
